name: Gunshell
version: '${project.version}-${git.commit.id.describe-short}'
website: 'https://www.spigotmc.org/resources/76350/'
main: com.jazzkuh.gunshell.GunshellPlugin
api-version: 1.13
description: "Add guns, melee weapons and throwables to your Minecraft server."
authors: [Jazzkuh]
softdepend: [WorldGuard]
commands:
  gunshell:
    aliases: [gs, gun, weapons, weapon, mtwapens, mtwapen]
